### ISSUE TITLE
no module 'util'

### ISSUE THREAD

**Issue by cataclysmic** [tobiasraabe/otree_virtual_machine_manager#30]
Here is the traceback:

```
otree@sms:~$ ovmm list_user
Traceback (most recent call last):
  File "/usr/local/bin/ovmm", line 11, in <module>
    load_entry_point('ovmm==0.1.0', 'console_scripts', 'ovmm')()
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ovmm-0.1.0-py2.7.egg/ovmm/cli.py", line 64, in list_user
    from .commands.list_user import list_user as list_usr
  File "/usr/local/lib/python2.7/dist-packages/ovmm-0.1.0-py2.7.egg/ovmm/commands/__init__.py", line 18, in <module>
    raise e
AttributeError: 'module' object has no attribute 'util'


```

**Comment by tobiasraabe** [comment]
Fixed in #32
